[masters]
master_node ansible_host=54.167.104.173
[workers]
worker_node ansible_host=35.172.181.70
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa_devops
ansible_ssh_common_args='-o StrictHostKeyChecking=no'




